export * from "./seo/seo"
export * from "./SideMenu"
export * from "./Home"
export * from "./About"
export * from "./Stack"
export * from "./Contact"
export * from "./Studies"
export * from "./Projects"
